version: '3.8'

services:
  # ABB Bridge Service - Main TCP bridge
  abb-bridge:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: abb-klipper-bridge
    ports:
      - "1234:1234"  # ABB robot connection port
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./logs:/app/logs
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    restart: unless-stopped
    networks:
      - abb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # File Converter Service (Optional - for batch processing)
  converter-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: abb-converter
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./config.toml:/app/config.toml:ro
    working_dir: /app
    command: ["python3", "-m", "converter", "--help"]  # Change this to your actual converter command
    restart: "no"  # Only run on demand
    networks:
      - abb-network
    profiles:
      - converter  # Only start when explicitly requested

networks:
  abb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  logs:
  input:
  output:
