name: Docs
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build Docs
        run: cargo doc --no-deps
      - name: Create staging directory
        run: mkdir target/doc-staging  # Create a temporary directory
      - name: Copy files to staging
        run: cp -r target/doc/ABB_Klipper_Middleware/* target/doc-staging/  # Copy everything
      - name: Copy index.html to root
        run: cp target/doc-staging/index.html target/doc-staging/index.html # Copy index.html to the root
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc-staging  # Upload from the staging directory

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
